version: '3.10'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:5001
    volumes:
      - .:/code
    ports:
      - 5001:5001
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
