# Generated by Django 4.1.6 on 2023-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='membera',
            field=models.CharField(default='', max_length=100),
        ),
    ]
