# Generated by Django 4.1.6 on 2023-02-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0002_tournament_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_teams',
            field=models.ManyToManyField(blank=True, related_name='tournament_teams', to='main_logic.team'),
        ),
    ]
