# Generated by Django 4.1.6 on 2023-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0002_tournament_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(blank=True, default='asd.txt', null=True, upload_to=''),
        ),
    ]
