# Generated by Django 4.1.6 on 2023-02-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0002_teammembership_membera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='membera',
        ),
    ]
