# Generated by Django 4.1.6 on 2023-03-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0002_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
