# Generated by Django 4.1.6 on 2023-02-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0003_alter_tournament_tournament_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='tournament',
        ),
    ]
