# Generated by Django 4.1.6 on 2023-08-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0003_remove_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('achievenment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_logic.achievementtype')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_logic.category')),
            ],
        ),
    ]
