# Generated by Django 4.1.6 on 2023-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0004_remove_questiontype_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament',
            field=models.ManyToManyField(related_name='questiontype', to='main_logic.questiontype'),
        ),
    ]
