# Generated by Django 4.1.6 on 2023-02-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0006_rename_tournament_tournament_tournament_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_questions',
            new_name='questiontypes',
        ),
    ]
