# Generated by Django 4.1.6 on 2023-02-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_logic', '0007_rename_tournament_questions_tournament_questiontypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
