# Generated by Django 4.1.6 on 2023-02-09 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('group_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('team_avatar', models.ImageField(default='teams.jpg', upload_to='static/teams_avatar/')),
                ('team_leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
