# Generated by Django 4.1.6 on 2023-02-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
