# Generated by Django 4.1.6 on 2023-02-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='following',
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.player')),
            ],
            options={
                'unique_together': {('user', 'follower')},
            },
        ),
    ]
