# Generated by Django 4.1.6 on 2023-02-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_player_following_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=8, unique=True)),
                ('players', models.ManyToManyField(to='accounts.player')),
            ],
        ),
    ]
