# Generated by Django 4.1.6 on 2023-02-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/players_avatar/'),
        ),
    ]
