# Generated by Django 4.1.6 on 2023-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
