# Generated by Django 4.1.6 on 2023-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_group_players_group_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
